export * from "./hotelSchema";
export * from "./faqSchema";
export * from "./roomsSchema";
export * from "./localBusinessSchema";
export * from "./howToSchema";
export * from "./breadcrumbSchema";
export * from "./blogSchema";
export * from "./corporateSchema";
export * from "./websiteSchema";
